version: "2"
services:
    call_zetk_in:
        build: ./
        image: poeditorul
        volumes:
            - "${CALL_ZETK_IN_LOCALE_PATH}:/var/locale"
        environment:
            POEDITOR_API_KEY: ${POEDITOR_API_KEY}
            POEDITOR_PROJECT_ID: ${CALL_ZETK_IN_PROJECT_ID}
            TARGET_LANGUAGE: ${TARGET_LANGUAGE}

    organize_zetk_in:
        build: ./
        image: poeditorul
        volumes:
            - "${ORGANIZE_ZETK_IN_LOCALE_PATH}:/var/locale"
        environment:
            POEDITOR_API_KEY: ${POEDITOR_API_KEY}
            POEDITOR_PROJECT_ID: ${ORGANIZE_ZETK_IN_PROJECT_ID}
            TARGET_LANGUAGE: ${TARGET_LANGUAGE}

    www_zetk_in:
        build: ./
        image: poeditorul
        volumes:
            - "${WWW_ZETK_IN_LOCALE_PATH}:/var/locale"
        environment:
            POEDITOR_API_KEY: ${POEDITOR_API_KEY}
            POEDITOR_PROJECT_ID: ${WWW_ZETK_IN_PROJECT_ID}
            TARGET_LANGUAGE: ${TARGET_LANGUAGE}

    ps_sms:
        build: ./
        image: poeditorul
        volumes:
            - "${PS_SMS_LOCALE_PATH}:/var/locale"
        environment:
            POEDITOR_API_KEY: ${POEDITOR_API_KEY}
            POEDITOR_PROJECT_ID: ${PS_SMS_PROJECT_ID}
            TARGET_LANGUAGE: ${TARGET_LANGUAGE}

    ps_email:
        build: ./
        image: poeditorul
        volumes:
            - "${PS_EMAIL_LOCALE_PATH}:/var/locale"
        environment:
            POEDITOR_API_KEY: ${POEDITOR_API_KEY}
            POEDITOR_PROJECT_ID: ${PS_EMAIL_PROJECT_ID}
            TARGET_LANGUAGE: ${TARGET_LANGUAGE}
